print('1 - Add new employee')
print('2 - Add new Admin')
print('3 - Remove current employee by the employee email')
print('4 - Edit specific current employee data ')
print('Please choice one of following ones: ')